#!/usr/bin/env python3
from pathlib import Path
import sys

SCRIPT_DIR = Path(__file__).resolve().parent
sys.path.insert(0, str(SCRIPT_DIR))

from douyin_dl.cli import main  # type: ignore

if __name__ == "__main__":
    main()


